id: reporting_baseline
name: Baseline reporting
description: A reporting extension for baseline ML approach
authors: 
  - Abdelkader Elmahdaouy
  - Abdellah Elmekki
  - Soufiane Oualil
  - Ismail Berrada
  - Zakaria Yartaoui

license: BSD
version: 1.0

runtime: 
  name: extension.py

# dependencies: dependecies # TODO
requirements: requirements.txt # .yaml

# plugins:
#   - plugin1
#   - plugin2

log:
  dir: ./logs
  # Setting the log level: CRITICAL, ERROR, WARNING, INFO, DEBUG
  level: DEBUG 
  

repository: https://github.com/path/to/repository.git


# TODO: Comment each use case
channels:
  subscribe: [baselineInference]

# Additional options for custom uses
# Examples: logging to server
# options:
#   logstash:
#     # url: http://example.com/
#     port: port
#     index: index_name
#     keywords: []
#   elastic:
#     # url: http://example.com
#     index: index_name
    